name: .NET

on:
  push:
    branches: [ dotdevelop_tryBuild ]
  pull_request:
    branches: [ dotdevelop_tryBuild ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore dependencies
      run: dotnet restore LibGit2Sharp.sln
    - name: Build
      run:  dotnet build --no-restore LibGit2Sharp.sln
    - name: Pack
      run: |
            echo running on branch $(echo ${GITHUB_SHA} | cut -c1-10)
            dotnet pack --include-symbols -c Release LibGit2Sharp.sln
            ls ./bin/Packages/Release/
           
    - name: Short Sha
      id: short-sha
      run:  echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-10) "
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHORT_SHA: ${{ steps.short-sha.outputs.short_sha }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./bin/Packages/Release/LibGit2Sharp.0.27.0-preview-g${{ steps.short-sha.outputs.short_sha }}.nupkg
          asset_name: LibGit2Sharp.0.27.0-preview-g${{ steps.short-sha.outputs.short_sha  }}.nupkg
          asset_content_type: application/nupkg      
      
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore dependencies
      run: dotnet restore LibGit2Sharp.sln
    - name: Build
      run: dotnet build --no-restore LibGit2Sharp.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal LibGit2Sharp.sln
