name: .NET

on:
  push:
    branches: [ dotdevelop_tryBuild ]
  pull_request:
    branches: [ dotdevelop_tryBuild ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore dependencies
      run: dotnet restore LibGit2Sharp.sln
    - name: Build
      run: dotnet build --no-restore LibGit2Sharp.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal LibGit2Sharp.sln
