name: .NET

on:
  push:
    branches: [ dd/issues/2 ]
  pull_request:
    branches: [ dd/issues/2 ]

jobs:
  build:

    runs-on: ubuntu-20.04

    container:
      image: "debian:buster"
      
    steps:
    - name: Dependencies
      run: |
        apt update
        apt upgrade -y
        apt install git apt-transport-https dirmngr gnupg ca-certificates wget autoconf intltool build-essential sed -y
        wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/debian stable-buster main" > /etc/apt/sources.list.d/mono-official-stable.list
        apt update
        apt install mono-devel fsharp gtk-sharp2 -y
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore dependencies
      run: dotnet restore LibGit2Sharp.sln
    - name: Build
      run:  dotnet build --no-restore LibGit2Sharp.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal LibGit2Sharp.sln
   
